name: at_utils
description: Utility library for at projects.
version: 1.0.0
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logging: ^0.11.4
  yaml: ^2.2.0
  crypto: ^2.1.5
  at_commons:
    git:
      url: git@github.com:atsign-foundation/at_tools.git
      path: at_commons
      ref: master
#dependency_overrides:
#  at_commons:
#    path: ../at_commons
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_process: ^1.0.5
