name: at_utils
description: A Dart library that contains various utility classes such as atSign, atmetadata, configuration, and logger.
documentation: https://atsign.dev/docs/
version: 2.0.2
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.1
  yaml: ^3.1.0
  crypto: ^3.0.1
  at_commons: ^2.0.2
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.0
  test_process: ^2.0.0
