name: at_pkam
description: A command-line utility to generate PKAM digest
version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypton: ^2.0.1
  encrypt: ^5.0.0
  archive: ^3.1.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
