name: at_cli
description: A command line utility for at protocol commands.
version: 1.0.0
homepage: https://atsign.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  at_lookup:
    git:
      url: git://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: master

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
