name: at_cli
description: A command line utility for at protocol commands.
version: 1.1.0
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^2.1.1
  at_lookup: ^2.0.3
#  at_lookup:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: null_safety
#      version: ^1.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
