name: at_commons
description: at_commons library will be used for commonly used components in implementation of the @protocol.
version: 1.1.0
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.0
  test_process: ^2.0.0
