name: at_commons
description: Library for commonly used components
version: 1.0.0
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_process: ^1.0.5


