name: at_cram
description: A command-line utility to generate CRAM digest
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
