# The @Protocol root server configurations.

root_server:
  # The port on which root server runs.
  port: 64
  host: 'vip.ve.atsign.zone'

# The @Protocol application log configurations
log:
  debug: false

auth:
  reuired: true
  mode: cram #cram or pkam
  key_file_location: '/home/nareshg/git/atsign/digest/bin/@murali'
  at_sign: '@murali'