# The @Protocol root server configurations.

root_server:
  # The port on which root server runs.
  port: 64
  host: 'root.atsign.wtf'

# The @Protocol application log configurations
log:
  debug: false

auth:
  reuired: true
  mode: pkam #cram or pkam
  key_file_location: 'bin/@alice.atKeys'
  at_sign: '@alice'