name: at_cli
description: A command line utility for at protocol commands.
version: 3.0.0
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  at_lookup: ^3.0.7
  at_client: ^3.0.9
  crypton: ^2.0.1
  encrypt: ^5.0.0
  yaml_writer: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0
  test_process: ^2.0.0
