# This workflows runs when
# 1. pull_request raised to trunk branch.
# 2. tag created on at_tools repository
name: at_tools

on:
  push:
    tags:
      - v**
  pull_request:
    branches:
      - trunk

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - at_commons
          - at_utils

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: stable

      - name: Install dependencies in ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: dart pub get

      - name: Analyze project source in ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: dart analyze

      - name: Run tests in ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: dart test --concurrency=1
